-- COMANDO PARA CRIAR UM NOVO BANCO DE DADOS
CREATE DATABASE Aula001;

-- COMANDO PARA "ENTRAR" NO BANCO DE DADOS CRIADO
USE Aula001;

-- COMANDO PARA CRIAR UMA NOVA TABELA
CREATE TABLE Alunos (
  	RA int,
  	nome varchar(80),
  	fone varchar(30),
  	pai varchar(80),
  	mae varchar(80),
  	data_nasc date
);

--COMANDO PARA INSERIR (CADASTRAR) UM REGISTRO NA TABELA:
INSERT INTO Alunos
VALUES (102030, 'ANA', '16999450078', 'JOSE', 'MARIA', '2002-10-18'),
       (268975, 'PEDRO', '1699678595', 'PAULO', 'RAFAELA', '2000-09-28'),
       (596835, 'IVAN', '16999450256', 'AUGUSTO', 'PATRICIA', '2019-04-20');
 
--COMANDO PARA SELECIONAR TODOS OS REGISTROS DE UMA TABELA:
SELECT * FROM Alunos;
  
--COMANDO PARA ACRESCENTAR UMA COLUNA NOVA A TABELAS:
ALTER TABLE Alunos
ADD email varchar(50);
  
--COMANDO PARA EXCLUIR UMA COLUNA DA TABELA:
ALTER TABLE Alunos
DROP COLUMN pai;

--COMANDO PARA ATUALIZAR VALORES DE UMA COLUNA NA TABELA:
--CUIDADO! ESTE COMANDO PRECISA DE UM FILTRO PARA NAO AFETAR TODAS AS LINHAS DA TABELA!
UPDATE Alunos SET email = 'contato@Alunos.com.br'
WHERE RA = 102030;
  
--O COMANDO WHERE PODE ER USADO PARA FILTRAR LINHAS DA TABELA JUNTO COM OUTROS COMANDOS. EX:
SELECT * from Alunos
WHERE RA > 150000;
  
SELECT * from Alunos
WHERE mae <> 'ANA';
  
--COMANDO PAR EXCLUIR REGISTRO DA TABELA (APAGAR A LINHA):
DELETE Alunos
WHERE mae = 'PATRICIA';
 
--ORDERNAR O RESULTADO DA CONSULTA:
SELECT * from Alunos
ORDER BY data_nasc DESC;

--COMANDO PARA EXCLUIR A TABELA
DROP TABLE Alunos;